export const LOAD_TRANSACTION_LIST = 'LOAD_TRANSACTION_LIST';
export const LOAD_TRANSACTION_LIST_SUCCESS = 'LOAD_TRANSACTION_LIST_SUCCESS';
export const LOAD_TRANSACTION_LIST_ERROR = 'LOAD_TRANSACTION_LIST_ERROR';

export const REFUND = 'REFUND';
